variables:
- name: AzureDevOpsUrl
  value: $(System.TeamFoundationCollectionUri)
- name: AzureDevOpsAgentTag
  value: $(Build.BuildNumber)
- name: dockerRegistryServiceConnection
  value: 'ConnexionDocker'
- name: imageRepository
  value: 'aks-docker-agents'
- name: containerRegistry
  value: 'DockerRegisteryProject'
- name: dockerfilePath
  value: '**/DockerFiles/Dockerfile'
- name: ubuntuImageName
  value: 'ubuntu-latest'
- name: windowsImageName
  value: 'vs2017-win2016'
- name: Environment
  value: 'AKSenv.docker'
- name: DockerPoolName
  value: 'MON-Docker'

